create table if not exists public.members (
  "S.No." bigint not null generated by default as identity,
  member_id uuid not null default gen_random_uuid(),
  name text null,
  address_home text null,
  company_name text null,
  address_office text null,
  resident_landline text null,
  office_landline text null,
  mobile text null,
  email text null,
  trust_id uuid null,
  constraint members_pkey primary key ("S.No."),
  constraint members_member_id_key unique (member_id)
) tablespace pg_default;

create table if not exists public.registered_members (
  id uuid not null default gen_random_uuid(),
  trust_id uuid not null,
  member_id uuid not null,
  membership_number text null,
  role text null,
  joined_date date null,
  is_active boolean null default true,
  constraint registered_members_pkey primary key (id),
  constraint registered_members_trust_id_fkey foreign key (trust_id) references public."Trust" (id) on delete cascade,
  constraint registered_members_member_id_fkey foreign key (member_id) references public.members (member_id) on delete cascade
) tablespace pg_default;
