create table public."Trust" (
  id uuid not null default gen_random_uuid (),
  name text not null,
  icon_url text null,
  remark text null,
  created_at timestamp with time zone null default now(),
  terms_content text null,
  privacy_content text null,
  template_id uuid null,
  legal_name text null,
  superuser_id uuid null,
  gst_number text null,
  pan_number text null,
  website text null,
  email_id text null,
  remark1 text null,
  remark2 text null,
  remark3 text null,
  constraint hospitals_pkey primary key (id),
  constraint "Trust_superuser_id_fkey" foreign key (superuser_id) references superuser (id) on delete set null,
  constraint "Trust_template_id_fkey" foreign key (template_id) references app_templates (id) on delete set null
) tablespace pg_default;
